
;设置规则标志位
ruleset=🎯直连,[]GEOIP,private
ruleset=🎯直连,[]GEOSITE,googlefcm
ruleset=🚀手动,https://gist.github.com/LittleJake/0a1ded1adc32740e5f1f941c8be6d793/raw/3373e05c462686485c0a0ef76261cc3701ceaee7/enforce.list
ruleset=⛔拦截,https://gist.github.com/LittleJake/d4bd220bbfbcf7976fcc92368fb472a3/raw/bb76a0536671e3ecbdc51f1f4019da5218b9e915/blacklist.list
ruleset=🍃净化,[]GEOSITE,category-ads-all
ruleset=🍃净化,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Ruleset/ChinaOneKeyLogin.list
ruleset=🎯直连,https://gist.github.com/LittleJake/28596f47a767c1a5710d1a139d8a48e6/raw/f3e36259481c9ee2a5a73334ba23e8a0f4e8e486/geo_direct.list
ruleset=🎯直连,[]GEOIP,CN
ruleset=🎯直连,https://gist.github.com/LittleJake/0215ca64ad083659a6de44bb66ac231d/raw/f1aeb79f84fbcfeebc91478d2c781b5c9c890b7d/bypass.list
ruleset=🎯直连,https://gist.githubusercontent.com/LittleJake/e1e5299ece8bc02f91add764854e0a59/raw/7f12ae7dd511effd83074c55ac9b7ef6fde9d828/bypass_app.list
ruleset=📲电报,[]GEOSITE,telegram
ruleset=📲电报,[]GEOIP,telegram
ruleset=▶外媒,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
ruleset=🚀手动,[]GEOSITE,gfw
ruleset=🐟漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀手动`select`[]♻️自动`[]🚀全手动`[]🇺🇸`[]🇫🇷`[]🇩🇪`[]🇭🇰`[]4️⃣ `[]6️⃣ `[]DIRECT
custom_proxy_group=♻️自动`url-test`(^(?!.*(RLY)).*)`https://www.google.com/generate_204`300,,1,,true
custom_proxy_group=🚀全手动`select`.*
custom_proxy_group=▶外媒`select`[]🚀手动`[]🎯直连`[]🇺🇸`[]🇫🇷`[]🇩🇪`[]🇭🇰`[]4️⃣ `[]6️⃣ `[]DIRECT
custom_proxy_group=📲电报`select`[]🚀手动`[]🎯直连`[]🇺🇸`[]🇫🇷`[]🇩🇪`[]🇭🇰`[]4️⃣ `[]6️⃣ `[]DIRECT
custom_proxy_group=🎯直连`select`[]DIRECT`
custom_proxy_group=⛔拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🔒隐私`select`[]REJECT`[]DIRECT
custom_proxy_group=🇩🇪`select`(?=.*(德国)).*
custom_proxy_group=🇺🇸`select`(?=.*美国).*
custom_proxy_group=🇫🇷`select`(?=.*法国).*
custom_proxy_group=🇭🇰`select`(?=.*香港).*
custom_proxy_group=4️⃣ `url-test`\[v4\]`https://www.google.com/generate_204`300,,1,,true
custom_proxy_group=6️⃣ `url-test`\[v6\]`https://www.google.com/generate_204`300,,1,,true
custom_proxy_group=🚀落地`select`(^(?!.*(RLY)).*)
custom_proxy_group=🐟漏网之鱼`select`[]🎯直连`[]🚀手动`[]♻️自动`[]🇺🇸`[]4️⃣ `[]6️⃣ `[]DIRECT
;设置分组标志位
