udp_flag=true
ipv6=true

;设置规则标志位
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/LocalAreaNetwork.list
ruleset=🛑 全球拦截,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanAD.list
ruleset=🛑 全球拦截,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyList.list
ruleset=🛑 全球拦截,https://cdn.jsdelivr.net/gh/LittleJake/LittleJake@rm/mobile_ad.list
ruleset=🔒 隐私保护,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanEasyPrivacy.list
ruleset=🍃 应用净化,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/BanProgramAD.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/LittleJake/LittleJake@rm/bypass.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Apple.list
ruleset=📲 电报信息,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/Telegram.list
ruleset=🌍 国外媒体,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ProxyGFWlist.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaIp.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaCompanyIp.list
ruleset=🎯 全球直连,https://cdn.jsdelivr.net/gh/ACL4SSR/ACL4SSR@master/Clash/ChinaMedia.list
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]🇷🇺 RU`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=♻️ 自动选择LB`load-balance`.*`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]🇷🇺 RU`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT
custom_proxy_group=📲 电报信息`select`[]🇷🇺 RU`[]🚀 节点选择`[]🎯 全球直连`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT
custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]🇷🇺 RU`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]🇷🇺 RU`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🔒 隐私保护`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`[]🇭🇰 HK`[]🇸🇬 SG`[]🇯🇵 JP`[]🇺🇸 US`[]🇹🇼 TW`[]🇳🇱 NL`[]🇷🇺 RU`[]4️⃣ IPv4`[]6️⃣ IPv6`[]🐎trojan`[]🐎trojan LB`[]🐎trojan 🇨🇳中继`[]DIRECT
custom_proxy_group=🇷🇺 RU`select`(?=.*俄罗斯).*`https://www.google.ru/generate_204`60,,50
custom_proxy_group=🇳🇱 NL`select`(?=.*阿姆斯特丹).*`https://www.google.nl/generate_204`60,,50
custom_proxy_group=🇸🇬 SG`select`(?=.*新加坡).*`https://www.google.com.sg/generate_204`60,,50
custom_proxy_group=🇯🇵 JP`select`(?=.*(日|东京)).*`https://www.google.co.jp/generate_204`60,,50
custom_proxy_group=🇺🇸 US`select`(?=.*美).*`https://www.google.com/generate_204`60,,50
custom_proxy_group=🇭🇰 HK`select`(?=.*港).*`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=🇹🇼 TW`select`(?=.*台).*`https://www.google.com.tw/generate_204`60,,50
custom_proxy_group=6️⃣ IPv6`url-test`.*(?=.*v6)`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=4️⃣ IPv4`url-test`.*(?=.*v4)`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=🐎trojan`url-test`.*(?=.*TROJAN)`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=🐎trojan LB`load-balance`.*(?=.*TROJAN)`https://www.google.com.hk/generate_204`60,,50
custom_proxy_group=🐎trojan 🇨🇳中继`load-balance`.*(?=.*relay).*`https://www.google.com.hk/generate_204`60,,50
;设置分组标志位